wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    session_history: code/_session_history.ipynb
    start_time: 1661059700.233957
    t:
      1:
      - 53
      - 55
      2:
      - 53
      - 55
      3:
      - 2
      - 23
      4: 3.9.13
      5: 0.13.1
      8:
      - 1
      - 5
